# inhibit_all_warnings!
require_relative '../../node_modules/react-native/scripts/react_native_pods'
require_relative '../../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.4'

target 'HybridNavigation' do
    pod 'HybridNavigation', :path => '../../'

    config = use_native_modules!
    # flags = get_default_flags()

    use_react_native!(
        :path => config[:reactNativePath],
        # to enable hermes on iOS, change `false` to `true` and then install pods
        :hermes_enabled => false,
        :fabric_enabled => false,
        # An absolute path to your application root.
        :app_path => "#{Pod::Config.instance.installation_root}/.."
    )
end

