import { NativeEventEmitter } from 'react-native';
declare const NavigationModule: any;
declare const EventEmitter: NativeEventEmitter;
export declare const ON_COMPONENT_RESULT: string;
export declare const ON_BAR_BUTTON_ITEM_CLICK: string;
export declare const ON_COMPONENT_APPEAR: string;
export declare const ON_COMPONENT_DISAPPEAR: string;
export declare const ON_DIALOG_BACK_PRESSED: string;
export declare const ON_COMPONENT_MOUNT: string;
export declare const EVENT_SWITCH_TAB: string;
export declare const EVENT_NAVIGATION: string;
export declare const EVENT_SET_ROOT_COMPLETED: string;
export declare const KEY_REQUEST_CODE: string;
export declare const KEY_RESULT_CODE: string;
export declare const KEY_RESULT_DATA: string;
export declare const KEY_SCENE_ID: string;
export declare const KEY_MODULE_NAME: string;
export declare const KEY_INDEX: string;
export declare const KEY_ACTION: string;
export declare const KEY_ON: string;
export { EventEmitter, NavigationModule };
