import { NativeModules, NativeEventEmitter } from 'react-native';
const NavigationModule = NativeModules.NavigationHybrid;
const HBDEventEmitter = NativeModules.HBDEventEmitter;
const EventEmitter = new NativeEventEmitter(HBDEventEmitter);
export const ON_COMPONENT_RESULT = HBDEventEmitter.ON_COMPONENT_RESULT;
export const ON_BAR_BUTTON_ITEM_CLICK = HBDEventEmitter.ON_BAR_BUTTON_ITEM_CLICK;
export const ON_COMPONENT_APPEAR = HBDEventEmitter.ON_COMPONENT_APPEAR;
export const ON_COMPONENT_DISAPPEAR = HBDEventEmitter.ON_COMPONENT_DISAPPEAR;
export const ON_DIALOG_BACK_PRESSED = HBDEventEmitter.ON_DIALOG_BACK_PRESSED;
export const ON_COMPONENT_MOUNT = HBDEventEmitter.ON_COMPONENT_MOUNT;
export const EVENT_SWITCH_TAB = HBDEventEmitter.EVENT_SWITCH_TAB;
export const EVENT_NAVIGATION = HBDEventEmitter.EVENT_NAVIGATION;
export const EVENT_SET_ROOT_COMPLETED = HBDEventEmitter.EVENT_SET_ROOT_COMPLETED;
export const KEY_REQUEST_CODE = HBDEventEmitter.KEY_REQUEST_CODE;
export const KEY_RESULT_CODE = HBDEventEmitter.KEY_RESULT_CODE;
export const KEY_RESULT_DATA = HBDEventEmitter.KEY_RESULT_DATA;
export const KEY_SCENE_ID = HBDEventEmitter.KEY_SCENE_ID;
export const KEY_MODULE_NAME = HBDEventEmitter.KEY_MODULE_NAME;
export const KEY_INDEX = HBDEventEmitter.KEY_INDEX;
export const KEY_ACTION = HBDEventEmitter.KEY_ACTION;
export const KEY_ON = HBDEventEmitter.KEY_ON;
export { EventEmitter, NavigationModule };
